### ISSUE TITLE
Incorrect status code

### ISSUE THREAD

**Issue by denizcdemirci** [irensaltali/serverlessapigateway#38]
When I send an incorrect value to the authorization header, I get a positive response with a status code of 200 OK instead of the expected 401. In this case, it should have returned 401.

For example, the incorrect request is as follows:
```BASH
curl 'https://api.wope.com/properties/space/project' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9, Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
```

**Comment by irensaltali** [comment]
Fixed with #43
