### ISSUE TITLE
Create JSON Schema Definition

### ISSUE THREAD

**Issue by irensaltali** [irensaltali/serverlessapigateway#4]
Create a JSON Schema definition that reflects the structure and requirements of the JSON configuration model. Include specifications such as data types, required attributes, and validation patterns to ensure configuration integrity. Use this schema for automatic validation of configuration files.

**Comment by gkocyigit** [comment]
This specification can be used as JSON Schema definition: https://json-schema.org/. There are a lot of validator of this schema definition (including [CF Worker](https://github.com/cfworker/cfworker/blob/main/packages/json-schema/README.md)

**Comment by irensaltali** [comment]
@gkocyigit You can check the PR
